import { useEffect, useState } from 'react';
import { useForm } from 'react-hook-form';
import { useNavigate, useParams } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import toast from 'react-hot-toast';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { MediaPicker } from '@/features/media/MediaPicker';
import { SearchableMultiSelect } from '@/components/ui/SearchableMultiSelect';
import { DynamicAttributeFields } from './DynamicAttributeFields';
import { VariantEditModal } from './VariantEditModal';
import { SeoSettingsSection } from '@/features/posts/SeoSettingsSection';
import { ProductAssociationsEditor } from './ProductAssociationsEditor';
import { ProductOptionsEditor } from './ProductOptionsEditor';
import { productDefaults, productPayload, validateRequiredAttributes, type ProductFormValues } from './ProductSchema';
import { useDeleteProductVariant, useGenerateProductVariants, useProduct, useProductLookups, useProductPreviewUrl, useSaveProductOptions, useUpdateProduct, useUpdateProductVariant, type ProductMedia, type ProductVariant, type SaveProductOptionsPayload, type TaxClass, type UpdateVariantPayload } from './api';

export function ProductFormPage() {
  const { id } = useParams(); const productId = Number(id); const navigate = useNavigate(); const { t } = useTranslation(); const productQuery = useProduct(productId); const lookups = useProductLookups(); const updateMutation = useUpdateProduct(); const variantMutation = useUpdateProductVariant(); const saveOptionsMutation = useSaveProductOptions(); const generateVariantsMutation = useGenerateProductVariants(); const deleteVariantMutation = useDeleteProductVariant(); const previewMutation = useProductPreviewUrl(); const [editingVariant, setEditingVariant] = useState<ProductVariant | null>(null);
  const { register, control, handleSubmit, reset, watch, setValue, getValues, setError, formState: { errors, isDirty } } = useForm<ProductFormValues>(); const product = productQuery.data; const media = watch('media') ?? []; const collections = watch('collections') ?? []; const status = watch('status');
  useEffect(() => { if (product) reset(productDefaults(product)); }, [product?.id, product?.updated_at, reset]);
  if (productQuery.isLoading || !product) return <div className="flex h-64 items-center justify-center">{productQuery.isError ? <span className="text-red-600">{(productQuery.error as Error).message}</span> : <div className="h-7 w-7 animate-spin rounded-full border-2 border-primary border-t-transparent"/>}</div>;
  async function save(values: ProductFormValues) { const attrErrors = validateRequiredAttributes(product!.product_attributes, values.attributes); if (Object.keys(attrErrors).length) { Object.entries(attrErrors).forEach(([path, message]) => setError(`attributes.${path}` as any, { message: t(message) })); return; } try { const updated = await updateMutation.mutateAsync({ id: productId, payload: productPayload(values) }); toast.success(t('products.update_success')); reset(productDefaults(updated)); } catch (error: any) { const slugError = error?.status === 422 ? error?.data?.errors?.slug?.[0] : null; if (slugError) setError('slug', { message: slugError }); toast.error(error.message || t('common.error_occurred')); } }
  async function updateVariant(variant: ProductVariant, payload: UpdateVariantPayload) { try { await variantMutation.mutateAsync({ productId, variantId: variant.id, payload }); toast.success(t('products.variant_update_success')); } catch (error: any) { toast.error(error.message || t('common.error_occurred')); throw error; } }
  async function saveModalVariant(payload: UpdateVariantPayload) { if (!editingVariant) return; try { await updateVariant(editingVariant, payload); setEditingVariant(null); } catch { /* Keep the editor open after a failed save. */ } }
  async function saveOptions(payload: SaveProductOptionsPayload) { try { await saveOptionsMutation.mutateAsync({ productId, payload }); toast.success(t('products.options_save_success')); } catch (error: any) { toast.error(error.message || t('common.error_occurred')); throw error; } }
  async function generateVariants() { try { await generateVariantsMutation.mutateAsync({ productId }); toast.success(t('products.variants_generate_success')); } catch (error: any) { toast.error(error.message || t('common.error_occurred')); throw error; } }
  async function deleteVariant(variant: ProductVariant) { try { await deleteVariantMutation.mutateAsync({ productId, variantId: variant.id }); toast.success(t('products.variant_delete_success')); } catch (error: any) { toast.error(error.message || t('common.error_occurred')); throw error; } }
  function previewProduct() { previewMutation.mutate(productId, { onSuccess: ({ url }) => { const anchor = document.createElement('a'); anchor.href = url; anchor.target = '_blank'; anchor.rel = 'noopener noreferrer'; document.body.appendChild(anchor); anchor.click(); anchor.remove(); }, onError: (error: any) => toast.error(error.message || t('common.error_occurred')) }); }
  function addMedia(selected: { id: string; url: string } | null) { if (!selected || media.some((item) => item.id === selected.id && item.source === 'curator')) return; setValue('media', [...media, { ...selected, source: 'curator', alt: '' }], { shouldDirty: true }); }
  function setMediaAlt(index: number, alt: string) { setValue('media', media.map((item, i) => (i === index ? { ...item, alt } : item)), { shouldDirty: true }); }
  function moveMedia(index: number, offset: number) { const next = [...media]; const target = index + offset; if (target < 0 || target >= next.length) return; [next[index], next[target]] = [next[target], next[index]]; setValue('media', next, { shouldDirty: true }); }
  return <><form onSubmit={handleSubmit(save)} className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
    <div className="mb-6 flex items-center justify-between"><div className="flex items-center gap-3"><Button type="button" variant="secondary" onClick={() => navigate('/products')}>← {t('common.back')}</Button><div><h1 className="text-2xl font-bold text-slate-900">{displayName(product)}</h1><p className="text-sm text-slate-500">{product.product_type.name}</p></div></div><div className="flex items-center gap-3"><span className="text-xs text-slate-400">{isDirty ? t('products.unsaved') : t('products.saved')}</span><Button type="button" variant="secondary" disabled={previewMutation.isPending} onClick={previewProduct}>{previewMutation.isPending ? t('products.preview_loading') : t('products.preview')}</Button></div></div>
    <div className="grid gap-6 lg:grid-cols-12"><main className="space-y-6 lg:col-span-8">
      <Card className="p-6"><h2 className="mb-5 text-lg font-semibold">{t('products.title_description')}</h2><DynamicAttributeFields definitions={product.product_attributes} register={register as any} control={control as any} errors={(errors.attributes ?? {}) as any} afterHandle={{ name: <div className="mt-5"><label className="mb-1 block text-sm font-medium text-slate-700">{t('products.slug')}</label><input {...register('slug')} className="h-10 w-full rounded-lg border border-slate-200 px-3 text-sm"/>{status === 'published' && <p className="mt-1 text-xs text-amber-700">{t('products.slug_published_warning')}</p>}{errors.slug && <p className="mt-1 text-xs text-red-600">{errors.slug.message}</p>}</div> }}/></Card>
      {!product.has_variants && <SinglePricing variant={product.variants[0]} currency={product.default_currency.code} taxClasses={product.tax_classes} isSaving={variantMutation.isPending} onSave={updateVariant} t={t}/>}<ProductOptionsEditor options={product.product_options} variants={product.variants} isSavingOptions={saveOptionsMutation.isPending} isGenerating={generateVariantsMutation.isPending} isDeleting={deleteVariantMutation.isPending} onSaveOptions={saveOptions} onGenerate={generateVariants} onEditVariant={setEditingVariant} onDeleteVariant={deleteVariant}/><ProductAssociationsEditor productId={productId}/><SeoSettingsSection control={control as any} register={register as any} setValue={setValue as any} getValues={getValues as any} titleKey="attributes.name" contentKey="attributes.description" mediaContext="product" contentType="product"/><Card className="space-y-4 p-5"><div><h2 className="text-lg font-semibold">{t('products.seo_advanced')}</h2><p className="mt-1 text-sm text-slate-500">{t('products.seo_advanced_help')}</p></div><label className="block"><span className="mb-1 block text-sm font-medium text-slate-700">{t('products.canonical_url')}</span><input {...register('seo.canonical_url')} type="url" placeholder="https://" className="h-10 w-full rounded-lg border border-slate-200 px-3 text-sm"/></label><label className="flex items-center gap-3 text-sm text-slate-700"><input {...register('seo.is_indexable')} type="checkbox" className="rounded border-slate-300 text-primary focus:ring-primary"/>{t('products.is_indexable')}</label><label className="flex items-center gap-3 text-sm text-slate-700"><input {...register('seo.is_followable')} type="checkbox" className="rounded border-slate-300 text-primary focus:ring-primary"/>{t('products.is_followable')}</label></Card>
    </main><aside className="space-y-6 lg:col-span-4 lg:sticky lg:top-20 self-start"><Button type="submit" variant="primary" className="w-full justify-center py-3" disabled={updateMutation.isPending}>{updateMutation.isPending ? t('common.saving') : t('common.save')}</Button><Card className="p-5"><h2 className="mb-3 font-semibold">{t('products.status')}</h2><select {...register('status')} className="h-10 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm"><option value="draft">{t('products.status_draft')}</option><option value="published">{t('products.status_published')}</option></select></Card><Card className="p-5"><h2 className="mb-5 text-lg font-semibold">{t('products.media')}</h2>{media.length > 0 && <div className="mb-5 space-y-4"><MediaTile key={`${media[0].source}-${media[0].id}`} item={media[0]} index={0} total={media.length} onMove={moveMedia} onRemove={() => setValue('media', media.slice(1), { shouldDirty: true })} onAltChange={(alt) => setMediaAlt(0, alt)} t={t}/>{media.length > 1 && <div className="grid grid-cols-2 gap-4">{media.slice(1).map((item, index) => <MediaTile key={`${item.source}-${item.id}`} item={item} index={index + 1} total={media.length} onMove={moveMedia} onRemove={() => setValue('media', media.filter((_, i) => i !== index + 1), { shouldDirty: true })} onAltChange={(alt) => setMediaAlt(index + 1, alt)} t={t}/>)}</div>}</div>}<MediaPicker context="product" value={null} onChange={addMedia}/></Card><Card className="p-5"><h2 className="mb-2 text-lg font-semibold">{t('products.collections')}</h2><p className="mb-4 text-sm text-slate-500">{t('products.collections_help')}</p><SearchableMultiSelect options={lookups.collectionOptions} value={collections} onChange={(value) => setValue('collections', value, { shouldDirty: true })} placeholder={t('products.search_collections')}/></Card><Card className="space-y-4 p-5"><h2 className="font-semibold">{t('products.organization')}</h2><label className="block"><span className="mb-1 block text-sm text-slate-600">{t('products.product_type')}</span><select value={product.product_type_id} disabled className="h-10 w-full rounded-lg border border-slate-200 bg-slate-100 px-3 text-sm"><option>{product.product_type.name}</option></select></label><label className="block"><span className="mb-1 block text-sm text-slate-600">{t('products.brand')}</span><select value={watch('brand_id') ?? ''} onChange={(e) => setValue('brand_id', e.target.value ? Number(e.target.value) : null, { shouldDirty: true })} className="h-10 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm"><option value="">{t('products.no_brand')}</option>{lookups.brands.map((brand) => <option key={brand.id} value={brand.id}>{brand.name}</option>)}</select></label></Card></aside></div>
  </form><VariantEditModal variant={editingVariant} taxClasses={product.tax_classes} isSaving={variantMutation.isPending} onClose={() => setEditingVariant(null)} onSave={saveModalVariant}/></>;
}
function displayName(product: any) { const name = product.product_attributes.find((a: any) => a.handle === 'name')?.value; return typeof name === 'string' ? name || 'Untitled product' : name?.en || name?.vi || 'Untitled product'; }
function MediaTile({ item, index, total, onMove, onRemove, onAltChange, t }: { item: ProductMedia; index: number; total: number; onMove: (index: number, offset: number) => void; onRemove: () => void; onAltChange: (alt: string) => void; t: any }) { return <div className="rounded-xl border p-2"><img src={item.url} alt={item.alt} className="h-32 w-full rounded-lg object-cover"/><input type="text" value={item.alt} onChange={(e) => onAltChange(e.target.value)} placeholder={t('products.alt_text_placeholder')} className="mt-2 h-8 w-full rounded border border-slate-200 px-2 text-xs"/><div className="mt-2 flex justify-between text-xs"><div><button type="button" disabled={index === 0} onClick={() => onMove(index, -1)} className="px-2 disabled:opacity-30">←</button><button type="button" disabled={index === total - 1} onClick={() => onMove(index, 1)} className="px-2 disabled:opacity-30">→</button></div><button type="button" onClick={onRemove} className="text-red-600">×</button></div></div>; }
function SinglePricing({ variant, currency, taxClasses, isSaving, onSave, t }: { variant?: ProductVariant; currency: string; taxClasses: TaxClass[]; isSaving: boolean; onSave: (variant: ProductVariant, payload: UpdateVariantPayload) => Promise<void>; t: any }) {
  const [expanded, setExpanded] = useState(false);
  async function save(payload: UpdateVariantPayload) { if (!variant) return; try { await onSave(variant, payload); setExpanded(false); } catch { /* Keep the accordion open after a failed save. */ } }
  return <Card className="p-6"><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold">{t('products.pricing')}</h2><p className="mt-1 text-sm text-slate-500">{variant ? `${variant.formatted_price ?? `${variant.base_price} ${currency}`} · ${variant.sku}` : t('products.no_variant')}</p></div>{variant && <Button type="button" variant="secondary" onClick={() => setExpanded((current) => !current)}>{t('common.edit')}</Button>}</div>{expanded && variant && <VariantEditModal inline variant={variant} taxClasses={taxClasses} isSaving={isSaving} onClose={() => setExpanded(false)} onSave={save}/>}</Card>;
}
