import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import toast from 'react-hot-toast';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { DeleteConfirmModal } from '@/components/ui/delete-confirm-modal';
import { ProductCreateModal } from './ProductCreateModal';
import { ProductRowActions } from './ProductRowActions';
import { useCreateProduct, useDeleteProduct, useProductLookups, useProducts, type ProductStatus, type ProductSummary } from './api';
import type { CreateProductValues } from './ProductSchema';

export function ProductsListPage() {
  const { t } = useTranslation(); const navigate = useNavigate();
  const [searchInput, setSearchInput] = useState(''); const [search, setSearch] = useState(''); const [status, setStatus] = useState<ProductStatus | ''>(''); const [brandId, setBrandId] = useState<number | ''>(''); const [typeId, setTypeId] = useState<number | ''>(''); const [page, setPage] = useState(1); const [createOpen, setCreateOpen] = useState(false); const [deleting, setDeleting] = useState<ProductSummary | null>(null);
  useEffect(() => { const timer = setTimeout(() => setSearch(searchInput), 400); return () => clearTimeout(timer); }, [searchInput]);
  useEffect(() => setPage(1), [search, status, brandId, typeId]);
  const query = useProducts({ search, status, brand_id: brandId, product_type_id: typeId, page }); const lookups = useProductLookups(); const createMutation = useCreateProduct(); const deleteMutation = useDeleteProduct();
  async function create(values: CreateProductValues) { try { const product = await createMutation.mutateAsync({ ...values, product_type_id: Number(values.product_type_id) }); toast.success(t('products.create_success')); setCreateOpen(false); navigate(`/products/${product.id}`); } catch (error: any) { toast.error(error.message || t('common.error_occurred')); } }
  return <div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
    <div className="mb-6 flex items-center justify-between"><div><h1 className="text-2xl font-bold text-slate-900">{t('products.title')}</h1><p className="mt-1 text-sm text-slate-500">{t('products.subtitle')}</p></div><Button variant="primary" onClick={() => setCreateOpen(true)}>+ {t('products.create')}</Button></div>
    <div className="grid gap-3 rounded-t-xl border border-b-0 border-slate-200 bg-white p-4 md:grid-cols-4"><Input value={searchInput} onChange={(e) => setSearchInput(e.target.value)} placeholder={t('products.search')} /><Select value={status} onChange={(v) => setStatus(v as ProductStatus | '')}><option value="">{t('products.all_statuses')}</option><option value="draft">{t('products.status_draft')}</option><option value="published">{t('products.status_published')}</option></Select><Select value={brandId} onChange={(v) => setBrandId(v ? Number(v) : '')}><option value="">{t('products.all_brands')}</option>{lookups.brands.map((b) => <option key={b.id} value={b.id}>{b.name}</option>)}</Select><Select value={typeId} onChange={(v) => setTypeId(v ? Number(v) : '')}><option value="">{t('products.all_product_types')}</option>{lookups.productTypes.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</Select></div>
    <div className="overflow-hidden rounded-b-xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full"><thead className="border-b bg-slate-50"><tr>{['product','product_type','brand','stock','price','status','updated','actions'].map((key) => <th key={key} className={`px-6 py-4 text-xs font-semibold uppercase tracking-wide text-slate-500 ${key === 'actions' ? 'text-right' : 'text-left'}`}>{t(`products.column_${key}`)}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">
      {query.isLoading ? <StateRow text={t('common.loading', 'Loading...')} /> : query.isError ? <StateRow text={(query.error as Error).message} error /> : !query.data?.data.length ? <StateRow text={t('products.empty')} /> : query.data.data.map((product) => <tr key={product.id} className="hover:bg-slate-50"><td className="px-6 py-4"><div className="flex items-center gap-3">{product.thumbnail ? <img src={product.thumbnail} className="h-12 w-12 rounded-lg object-cover" alt=""/> : <div className="h-12 w-12 rounded-lg bg-slate-100"/>}<div><button className="font-semibold text-slate-900 hover:text-primary" onClick={() => navigate(`/products/${product.id}`)}>{product.name}</button>{product.description && <p className="max-w-xs truncate text-xs text-slate-500">{product.description}</p>}</div></div></td><td className="px-6 py-4 text-sm">{product.product_type.name}</td><td className="px-6 py-4 text-sm">{product.brand?.name ?? '—'}</td><td className="px-6 py-4 text-sm font-medium">{product.total_stock}</td><td className="px-6 py-4 text-sm">{product.price?.formatted ?? '—'}</td><td className="px-6 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${product.status === 'published' ? 'bg-emerald-100 text-emerald-700' : 'bg-amber-100 text-amber-700'}`}>{t(`products.status_${product.status}`)}</span></td><td className="px-6 py-4 text-sm text-slate-500">{product.updated_at ? new Date(product.updated_at).toLocaleDateString() : '—'}</td><td className="px-6 py-4"><ProductRowActions product={product} onDelete={setDeleting}/></td></tr>)}
    </tbody></table></div>{query.data && query.data.meta.last_page > 1 && <div className="flex items-center justify-between border-t bg-slate-50 px-6 py-4"><span className="text-sm text-slate-500">{t('products.page_of', { current: query.data.meta.current_page, last: query.data.meta.last_page })}</span><div className="flex gap-2"><Button variant="secondary" disabled={page <= 1} onClick={() => setPage((p) => p - 1)}>{t('common.previous', 'Previous')}</Button><Button variant="secondary" disabled={page >= query.data.meta.last_page} onClick={() => setPage((p) => p + 1)}>{t('common.next', 'Next')}</Button></div></div>}</div>
    <ProductCreateModal open={createOpen} productTypes={lookups.productTypes} isSaving={createMutation.isPending} onClose={() => setCreateOpen(false)} onSubmit={create}/><DeleteConfirmModal open={Boolean(deleting)} onClose={() => setDeleting(null)} onConfirm={() => deleting && deleteMutation.mutate(deleting.id, { onSuccess: () => { toast.success(t('products.delete_success')); setDeleting(null); }, onError: (e) => toast.error(e.message) })} title={t('products.delete_title')} message={t('products.delete_confirm', { name: deleting?.name })} isLoading={deleteMutation.isPending}/>
  </div>;
}
function Select({ value, onChange, children }: { value: string | number; onChange: (value: string) => void; children: React.ReactNode }) { return <select value={value} onChange={(e) => onChange(e.target.value)} className="h-10 rounded-lg border border-slate-200 bg-white px-3 text-sm">{children}</select>; }
function StateRow({ text, error = false }: { text: string; error?: boolean }) { return <tr><td colSpan={8} className={`px-6 py-12 text-center text-sm ${error ? 'text-red-600' : 'text-slate-500'}`}>{text}</td></tr>; }
