import { useEffect } from 'react';
import { zodResolver } from '@hookform/resolvers/zod';
import { useForm } from 'react-hook-form';
import { useTranslation } from 'react-i18next';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { DynamicAttributeFields } from './DynamicAttributeFields';
import { variantDefaults, variantFormSchema, variantPayload, validateRequiredAttributes, type VariantFormValues } from './ProductSchema';
import type { ProductVariant, TaxClass, UpdateVariantPayload } from './api';

const dimensionUnits = ['mm', 'cm', 'm', 'in', 'ft']; const weightUnits = ['g', 'kg', 'lb', 'oz'];
export function VariantEditModal({ variant, taxClasses, isSaving, onClose, onSave }: { variant: ProductVariant | null; taxClasses: TaxClass[]; isSaving: boolean; onClose: () => void; onSave: (payload: UpdateVariantPayload) => Promise<void> }) {
  const { t } = useTranslation();
  const { register, handleSubmit, reset, setError, formState: { errors } } = useForm<VariantFormValues>({ resolver: zodResolver(variantFormSchema) });
  useEffect(() => { if (variant) reset(variantDefaults(variant)); }, [variant, reset]);
  if (!variant) return null;
  const submit = handleSubmit(async (raw) => { const parsed = variantFormSchema.parse(raw); const attrErrors = validateRequiredAttributes(variant.attributes, parsed.attributes); if (Object.keys(attrErrors).length) { Object.entries(attrErrors).forEach(([path, message]) => setError(`attributes.${path}` as any, { message: t(message) })); return; } await onSave(variantPayload(parsed)); });
  return <div className="fixed inset-0 z-[100] flex justify-end bg-slate-900/50" onMouseDown={onClose}><form onSubmit={submit} onMouseDown={(e) => e.stopPropagation()} className="h-full w-full max-w-3xl overflow-y-auto bg-white shadow-2xl">
    <div className="sticky top-0 z-10 flex items-center justify-between border-b bg-white px-6 py-4"><div><h2 className="text-xl font-bold">{t('products.edit_variant')}</h2><p className="text-sm text-slate-500">{variant.option_values.map((v) => `${v.option_name}: ${v.value_name}`).join(' / ') || variant.sku}</p></div><button type="button" onClick={onClose} className="text-2xl text-slate-400">×</button></div>
    <div className="space-y-7 p-6">
      <Section title={t('products.identifiers')}><div className="grid gap-4 sm:grid-cols-2"><TextField label={t('products.sku')} register={register('sku')} error={errors.sku?.message}/><TextField label="GTIN" register={register('gtin')}/><TextField label="MPN" register={register('mpn')}/><TextField label="EAN" register={register('ean')}/></div></Section>
      <Section title={t('products.pricing_inventory')}><div className="grid gap-4 sm:grid-cols-3"><TextField label={t('products.base_price')} register={register('base_price')} error={errors.base_price?.message}/><TextField label={t('products.stock')} type="number" register={register('stock')}/><TextField label={t('products.backorder')} type="number" register={register('backorder')}/><TextField label={t('products.unit_quantity')} type="number" register={register('unit_quantity')}/><TextField label={t('products.min_quantity')} type="number" register={register('min_quantity')}/><TextField label={t('products.quantity_increment')} type="number" register={register('quantity_increment')}/></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><label><span className="mb-1 block text-sm font-medium">{t('products.purchasable')}</span><select {...register('purchasable')} className="h-10 w-full rounded-lg border border-slate-200 px-3"><option value="always">{t('products.purchasable_always')}</option><option value="in_stock">{t('products.purchasable_stock')}</option><option value="in_stock_or_on_backorder">{t('products.purchasable_backorder')}</option></select></label><label><span className="mb-1 block text-sm font-medium">{t('products.tax_class')}</span><select {...register('tax_class_id')} className="h-10 w-full rounded-lg border border-slate-200 px-3">{taxClasses.map((tax) => <option key={tax.id} value={tax.id}>{tax.name}</option>)}</select></label><TextField label={t('products.tax_ref')} register={register('tax_ref')}/><label className="flex items-center gap-2 pt-7 text-sm"><input type="checkbox" {...register('shippable')} />{t('products.shippable')}</label></div></Section>
      <Section title={t('products.shipping')}><div className="grid gap-4 sm:grid-cols-2">{(['length','width','height'] as const).map((key) => <Dimension key={key} label={t(`products.${key}`)} valueRegister={register(`${key}_value`)} unitRegister={register(`${key}_unit`)} units={dimensionUnits}/>) }<Dimension label={t('products.weight')} valueRegister={register('weight_value')} unitRegister={register('weight_unit')} units={weightUnits}/></div></Section>
      {variant.attributes.length > 0 && <Section title={t('products.custom_fields')}><DynamicAttributeFields definitions={variant.attributes} register={register as any} errors={(errors.attributes ?? {}) as any}/></Section>}
    </div>
    <div className="sticky bottom-0 flex justify-end gap-3 border-t bg-white px-6 py-4"><Button type="button" variant="secondary" onClick={onClose}>{t('common.cancel')}</Button><Button type="submit" variant="primary" disabled={isSaving}>{isSaving ? t('common.saving', 'Saving...') : t('common.save')}</Button></div>
  </form></div>;
}
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section><h3 className="mb-4 border-b pb-2 text-base font-semibold text-slate-900">{title}</h3>{children}</section>; }
function TextField({ label, register, error, type = 'text' }: { label: string; register: any; error?: any; type?: string }) { return <label><span className="mb-1 block text-sm font-medium">{label}</span><Input type={type} {...register}/>{error && <span className="text-xs text-red-600">{String(error)}</span>}</label>; }
function Dimension({ label, valueRegister, unitRegister, units }: { label: string; valueRegister: any; unitRegister: any; units: string[] }) { return <div><span className="mb-1 block text-sm font-medium">{label}</span><div className="flex"><Input className="rounded-r-none" inputMode="decimal" {...valueRegister}/><select {...unitRegister} className="w-24 rounded-r-lg border border-l-0 border-slate-200 px-2"><option value="">—</option>{units.map((unit) => <option key={unit} value={unit}>{unit}</option>)}</select></div></div>; }
