services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: petposture-backend
    container_name: petposture-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: backend
      SERVICE_TAGS: dev
    volumes:
      - c:\laragon\www\petposture\backend:/var/www
    networks:
      - petposture-network

  nginx:
    image: nginx:alpine
    container_name: petposture-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - c:\laragon\www\petposture\backend:/var/www
      - c:\laragon\www\petposture\nginx\conf.d\:/etc/nginx/conf.d/
    networks:
      - petposture-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: petposture-frontend
    container_name: petposture-frontend
    restart: unless-stopped
    ports:
      - "3001:3000"
    volumes:
      - c:\laragon\www\petposture\frontend:/app
      - /app/node_modules
    networks:
      - petposture-network

networks:
  petposture-network:
    driver: bridge
