import { useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import toast from 'react-hot-toast';
import { Button } from '@/components/ui/button';
import { useOrder, useRefundOrder, useReturnOrder, type Order, type OrderAddress } from './api';

export function OrderDetailPage({ canRefund = true }: { canRefund?: boolean }) {
  const { t } = useTranslation();
  const navigate = useNavigate();
  const { id } = useParams();
  const query = useOrder(id);
  const refundMutation = useRefundOrder();
  const returnMutation = useReturnOrder();
  const [refundOpen, setRefundOpen] = useState(false);
  const [returnOpen, setReturnOpen] = useState(false);
  const [amount, setAmount] = useState('');
  const order = query.data;
  async function refund() { const numericAmount = amount.trim() === '' ? undefined : Number(amount); if (numericAmount !== undefined && (!(numericAmount > 0) || Number.isNaN(numericAmount))) { toast.error(t('orders.refund_amount_invalid')); return; } try { await refundMutation.mutateAsync({ id: order!.id, amount: numericAmount }); toast.success(t('orders.refund_success')); setRefundOpen(false); setAmount(''); } catch (error: any) { toast.error(error.message || t('common.error_occurred')); } }
  async function markReturned() { try { await returnMutation.mutateAsync({ id: order!.id }); toast.success(t('orders.return_success')); setReturnOpen(false); } catch (error: any) { toast.error(error.message || t('common.error_occurred')); } }
  if (query.isLoading) return <PageState text={t('common.loading')} />;
  if (query.isError || !order) return <PageState text={query.isError ? (query.error as Error).message : t('orders.not_found')} error />;
  const events = [...(order.order_events ?? [])].sort((left, right) => new Date(left.created_at ?? 0).getTime() - new Date(right.created_at ?? 0).getTime());
  return <div className="mx-auto max-w-5xl px-4 py-8 sm:px-6 lg:px-8">
    <Button variant="secondary" onClick={() => navigate('/orders')}>← {t('orders.back')}</Button>
    <div className="mt-6 flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-bold text-slate-900">{order.reference}</h1><p className="mt-1 text-sm text-slate-500">{order.customer_email}</p></div><div className="flex gap-2">{canRefund && <Button variant="danger" onClick={() => setRefundOpen(true)}>{t('orders.refund')}</Button>}<Button variant="secondary" onClick={() => setReturnOpen(true)}>{t('orders.mark_returned')}</Button></div></div>
    <div className="mt-6 grid gap-6 md:grid-cols-3">
      <section className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm md:col-span-2"><h2 className="text-lg font-semibold text-slate-900">{t('orders.summary')}</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><Detail label={t('orders.total')} value={displayMoney(order.total.decimal)}/><Detail label={t('orders.status')} value={order.status_label ?? order.status}/><Detail label={t('orders.payment_method')} value={paymentMethodDisplay(order)}/><Detail label={t('orders.payment_status')} value={order.payment_status_label ?? order.payment_status}/><Detail label={t('orders.fulfillment_status')} value={order.fulfillment_status_label ?? order.fulfillment_status}/><Detail label={t('orders.refund_status')} value={titleCase(order.refund_status)}/><Detail label={t('orders.refund_amount')} value={displayRefundMoney(order.refund_amount)}/>{order.coupon_code && <Detail label={t('orders.coupon')} value={order.coupon_code}/>}</div>{hasCustomerIpData(order) && <div className="mt-4 border-t border-slate-100 pt-4"><dt className="text-xs font-semibold uppercase tracking-wide text-slate-500">{t('orders.customer_ip')}</dt><dd className="mt-1 space-y-0.5 text-sm text-slate-900">{order.customer_ip && <p><span className="font-medium">{t('orders.ip')}:</span> {order.customer_ip}</p>}{order.customer_ip_location && <p><span className="font-medium">{t('orders.location')}:</span> {order.customer_ip_location}</p>}{order.customer_ip_isp && <p><span className="font-medium">{t('orders.isp')}:</span> {order.customer_ip_isp}</p>}{order.customer_user_agent && <p><span className="font-medium">{t('orders.user_agent')}:</span> {order.customer_user_agent}</p>}{order.customer_ip_service_type && <p><span className="font-medium">{t('orders.service')}:</span> {order.customer_ip_service_type}</p>}</dd></div>}</section>
      <div className="space-y-6">
        <section className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-semibold text-slate-900">{t('orders.attribution')}</h2><div className="mt-4 space-y-4"><Detail label={t('orders.origin')} value={displayValue(order.attribution_origin)}/><Detail label={t('orders.device_type')} value={displayValue(order.attribution_device_type)}/><Detail label={t('orders.session_page_views')} value={displayValue(order.attribution_session_page_views)}/></div></section>
        {hasFraudData(order) && <section className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-semibold text-slate-900">{t('orders.fraud_risk')}</h2><p className="mt-1 text-xs text-slate-500">{t('orders.fraud_risk_description')}</p><div className="mt-4 space-y-4"><div><dt className="text-xs font-semibold uppercase tracking-wide text-slate-500">{t('orders.risk_level')}</dt><dd className={`mt-1 inline-flex rounded-full px-2.5 py-0.5 text-sm font-semibold ${riskBadgeClass(order.fraud_risk_level)}`}>{titleCase(order.fraud_risk_level)}</dd></div><Detail label={t('orders.risk_score')} value={displayValue(order.fraud_risk_score)}/><Detail label={t('orders.note')} value={displayValue(order.fraud_seller_message)}/></div></section>}
      </div>
    </div>
    <Section title={t('orders.items')}><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b text-xs font-semibold uppercase tracking-wide text-slate-500"><tr><th className="pb-2">{t('orders.product')}</th><th className="pb-2">{t('orders.qty')}</th><th className="pb-2 text-right">{t('orders.unit_price')}</th><th className="pb-2 text-right">{t('orders.subtotal')}</th></tr></thead><tbody>{(order.lines ?? []).filter((line) => line.type !== 'shipping').map((line) => <tr key={line.id} className="border-b last:border-0"><td className="py-3">{line.description}</td><td className="py-3">{line.quantity}</td><td className="py-3 text-right">{displayMoney(line.unit_price)}</td><td className="py-3 text-right">{displayMoney(line.sub_total)}</td></tr>)}</tbody></table></div><div className="ml-auto mt-6 max-w-sm space-y-2 text-sm"><TotalRow label={t('orders.items_subtotal')} value={displayMoney(order.sub_total)}/><TotalRow label={`${t('orders.discount')}${order.coupon_code ? ` (${order.coupon_code})` : ''}`} value={displayMoney(order.discount_total)}/><TotalRow label={`${t('orders.shipping')}${order.shipping_label ? ` (${order.shipping_label})` : ''}`} value={displayMoney(order.shipping_total)}/><TotalRow label={t('orders.tax')} value={displayMoney(order.tax_total)}/><TotalRow label={t('orders.order_total')} value={displayMoney(order.total.decimal)} bold/></div></Section>
    <div className="grid gap-6 md:grid-cols-2"><Section title={t('orders.shipping_address')}><Address address={order.shipping_address}/></Section><Section title={t('orders.billing_address')}><Address address={order.billing_address}/></Section></div>
    <Section title={t('orders.timeline')}><ol className="space-y-4">{events.map((event, index) => <li key={`${event.type}-${event.created_at}-${index}`} className="border-l-2 border-slate-200 pl-4"><p className="font-medium text-slate-900">{event.title}</p>{event.detail && <p className="text-sm text-slate-500">{event.detail}</p>}<p className="text-xs text-slate-400">{event.created_at ? new Date(event.created_at).toLocaleString() : '—'}</p></li>)}</ol></Section>
    <ConfirmModal open={refundOpen} title={t('orders.refund')} onClose={() => setRefundOpen(false)} onConfirm={refund} loading={refundMutation.isPending}><label className="block text-sm font-medium text-slate-700">{t('orders.refund_amount')}<input type="number" min="0.01" step="0.01" value={amount} onChange={(event) => setAmount(event.target.value)} className="mt-1 block w-full rounded-lg border border-slate-200 px-3 py-2" /></label><p className="mt-2 text-sm text-slate-500">{t('orders.refund_full_amount_hint')}</p></ConfirmModal>
    <ConfirmModal open={returnOpen} title={t('orders.mark_returned')} onClose={() => setReturnOpen(false)} onConfirm={markReturned} loading={returnMutation.isPending}><p className="text-sm text-slate-500">{t('orders.return_confirm')}</p></ConfirmModal>
  </div>;
}
function PageState({ text, error = false }: { text: string; error?: boolean }) { return <div className={`p-8 text-center text-sm ${error ? 'text-red-600' : 'text-slate-500'}`}>{text}</div>; }
function displayMoney(value?: number | null) { return value == null ? '—' : `$${value.toFixed(2)}`; }
function displayRefundMoney(value?: number | null) { return value == null ? '—' : `$${(value / 100).toFixed(2)}`; }
function titleCase(value?: string | null) { return value ? value.replace(/[_-]/g, ' ').replace(/\b\w/g, (letter) => letter.toUpperCase()) : '—'; }
function displayValue(value?: string | number | null) { return value == null ? '—' : String(value); }
function hasFraudData(order: Order) { return order.fraud_risk_level != null || order.fraud_risk_score != null || order.fraud_seller_message != null; }
function hasCustomerIpData(order: Order) { return order.customer_ip != null || order.customer_ip_location != null || order.customer_ip_isp != null || order.customer_user_agent != null || order.customer_ip_service_type != null; }
function paymentMethodDisplay(order: Order) { const label = order.payment_label; if (!label) return '—'; if (!order.card_brand || !order.card_last4) return label; const brand = order.card_brand.charAt(0).toUpperCase() + order.card_brand.slice(1); return `${label} - ${brand} •••• ${order.card_last4}`; }
function riskBadgeClass(riskLevel?: string | null) { return riskLevel === 'highest' ? 'bg-red-100 text-red-700' : riskLevel === 'elevated' ? 'bg-yellow-100 text-yellow-700' : 'bg-emerald-100 text-emerald-700'; }
function TotalRow({ label, value, bold = false }: { label: string; value: string; bold?: boolean }) { return <div className={`flex justify-between gap-4 ${bold ? 'border-t pt-2 font-bold text-slate-900' : 'text-slate-600'}`}><span>{label}</span><span>{value}</span></div>; }
function Detail({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-1 text-sm text-slate-900">{value}</dd></div>; }
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="mt-6 rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-semibold text-slate-900">{title}</h2><div className="mt-4">{children}</div></section>; }
function Address({ address }: { address?: OrderAddress }) { if (!address) return <span className="text-sm text-slate-500">—</span>; return <div className="text-sm text-slate-600"><p>{[address.first_name, address.last_name].filter(Boolean).join(' ')}</p><p>{address.line_one}</p>{address.line_two && <p>{address.line_two}</p>}<p>{[address.city, address.state, address.postcode].filter(Boolean).join(', ')}</p><p>{address.country}</p><p>{address.phone}</p></div>; }
function ConfirmModal({ open, title, onClose, onConfirm, loading, children }: { open: boolean; title: string; onClose: () => void; onConfirm: () => void; loading: boolean; children: React.ReactNode }) { const { t } = useTranslation(); if (!open) return null; return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-900/60 p-4"><div className="w-full max-w-sm rounded-xl bg-white p-6 shadow-xl"><h2 className="text-lg font-bold text-slate-900">{title}</h2><div className="mt-4">{children}</div><div className="mt-6 flex justify-end gap-3"><Button variant="secondary" disabled={loading} onClick={onClose}>{t('common.cancel')}</Button><Button variant="danger" disabled={loading} onClick={onConfirm}>{t('common.confirm')}</Button></div></div></div>; }
