<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Resources\Api\PostResource;
use App\Models\BlogCategory;
use App\Models\Page;
use App\Models\Post;
use App\Traits\HttpResponses;
use Illuminate\Http\Request;

class ContentController extends Controller
{
    use HttpResponses;

    public function posts()
    {
        $posts = Post::where('status', 'published')
            ->where('published_at', '<=', now())
            ->with(['blogCategory', 'metadata', 'tags', 'seo'])
            ->latest()
            ->paginate(12);

        return PostResource::collection($posts);
    }

    public function post(Request $request, $slug)
    {
        $query = Post::where('slug', $slug);

        if (! $this->hasValidPreviewToken($request, $slug)) {
            $query->where('status', 'published');
        }

        $post = $query->with(['blogCategory', 'metadata', 'tags', 'seo'])->firstOrFail();

        return new PostResource($post);
    }

    /**
     * Draft posts are normally hidden from this endpoint. A signed preview
     * link (generated by the admin's "Preview" button) can bypass that.
     * Not a route-name-based signed URL: routes/api.php gets registered
     * twice (plain + /api/v1 alias, see bootstrap/app.php), so any named
     * route in that file collides with itself under route caching.
     */
    private function hasValidPreviewToken(Request $request, string $slug): bool
    {
        $expires = $request->query('expires');
        $token = $request->query('preview_token');

        if (! $expires || ! $token || now()->timestamp > (int) $expires) {
            return false;
        }

        $expected = hash_hmac('sha256', $slug.'|'.$expires, config('app.key'));

        return hash_equals($expected, (string) $token);
    }

    public function page($slug)
    {
        $page = Page::where('slug', $slug)
            ->where('is_active', true)
            ->firstOrFail();

        return response()->json([
            'data' => [
                'slug' => $page->slug,
                'title' => $page->title,
                'content' => $this->renderPlaceholders($page->content),
                'meta_title' => $page->meta_title,
                'meta_description' => $page->meta_description,
                'updated_at' => $page->updated_at,
            ],
        ]);
    }

    /**
     * Substitute {{business_phone}}/{{business_address}}/{{business_address_inline}}
     * tokens in page content with the live Settings values, so legal-page copy
     * stays in sync with admin edits instead of needing the phone/address
     * re-typed into every page's rich text separately.
     */
    private function renderPlaceholders(?string $content): ?string
    {
        if ($content === null) {
            return null;
        }

        $phone = setting('business_phone') ?: '+1 (916) 623-5368';
        $address = setting('business_address') ?: '1501 South Greeley Hwy, Ste C #1465, Cheyenne, WY 82007, United States';

        return str_replace(
            ['{{business_phone}}', '{{business_address}}', '{{business_address_inline}}'],
            [$phone, $this->formatAddressMultiline($address), $address],
            $content
        );
    }

    /**
     * "Street, City, State Zip, Country" -> "Street<br>City, State Zip<br>Country"
     * (3 display lines, not one per comma) — matches the standard mailing-address
     * layout: street / city+state+zip / country.
     */
    private function formatAddressMultiline(string $address): string
    {
        $parts = array_map('trim', explode(',', $address));

        if (count($parts) === 4) {
            [$street, $city, $stateZip, $country] = $parts;

            return "{$street}<br>{$city}, {$stateZip}<br>{$country}";
        }

        return str_replace(', ', '<br>', $address);
    }

    public function categories()
    {
        return response()->json([
            'data' => BlogCategory::all()->map(fn ($c) => [
                'id' => $c->id,
                'name' => $c->name,
                'slug' => $c->slug,
            ])->values(),
        ]);
    }
}
